name: Deploy GitHub Pages

on:
  push:
    branches:
      - develop # Cambia al nombre de tu rama principal si no es develop

jobs:
  build:
    runs-on: ubuntu-22.04 # Usamos una versión específica para evitar advertencias futuras

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 # Usa la versión compatible con tu proyecto

    - name: Install dependencies
      run: |
        cd frontend
        npm install

    - name: Build project
      run: |
        cd frontend
        npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: frontend/build